minddonyy/AlgorithmStudy

Comet/BOJ/1189/sol.cpp

- 문제 : [컴백홈](https://www.acmicpc.net/problem/1189)
- 플랫폼: 백준
- 난이도 : 실버1
- 시간 : 0ms
- 메모리 : 2024kb
```
int result;
int dy[4] = { -1, 1, 0, 0 };
int dx[4] = { 0, 0, -1, 1 };
int low, col, length;
void dfs(int y, int x, int cnt,vector<vector<bool>>& visited, vector<string>& map) {
if (y == 0 && x == col - 1) {
if (cnt == length) {
result++;
}
return;
}
if (cnt >= length) return;
for (int i = 0; i < 4; i++) {
tempy = y + dy[i]; tempx = x + dx[i];
if (tempy >= 0 && tempy < low && tempx >= 0 && tempx < col && map[tempy][tempx] != 'T' && !visited[tempy][tempx]) {
visited[tempy][tempx] = 1;
dfs(tempy, tempx, cnt + 1, visited, map);
visited[tempy][tempx] = 0;
}
}
return;
}
int main() {
result = 0;
cin …
```

[solved] BOJ/1189 문제해결

---

minsun/BOJ/1189/sol.py

- 문제 : 컴백홈
- 플랫폼: 백준
- 난이도 : 실버 1
- 시간 : 100ms
- 메모리 : 32412KB
```
import sys
sys.stdin = open('input.txt', 'r')
"""
첫 줄에 정수 R(1 ≤ R ≤ 5), C(1 ≤ C ≤ 5), K(1 ≤ K ≤ R×C)가 공백으로 구분되어 주어진다. 
두 번째부터 R+1번째 줄까지는 R×C 맵의 정보를 나타내는 '.'과 'T'로 구성된 길이가 C인 문자열이 주어진다.
"""
dxs = [-1, 1, 0, 0]
dys = [0, 0, -1, 1]
def gohome(start_x, start_y, cnt): # 시작위치와 카운트
global result
visited[start_x][start_y] = 1
if start_x == 0 and start_y == (C - 1):
if cnt == K:
result += 1
return
#델타탐색 .. 이거 눈감고도 하던 건데 오래만에 하니까 와 ... 반성합니다
for dx, dy in zip(dxs, dys):
nx = start_x + dx
ny = start_y + dy
if 0 <= nx < R and 0 <= ny < C and visited[nx][ny] != 1 and hansu_map[nx][ny] != 'T':
visited[nx][ny] = 1 #방문
gohome(nx, ny, cnt + 1) # 다음칸
visited[nx][ny] = 0 # 다시 방문취소해주고
R, C, K = map(int, input().split())
hansu_map = …
```

[Solve] : [BOJ] 1189 컴백홈 - 문제 해결

---

Comet/SWEA/13038/sol.cpp

- 문제 : [교환학생](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=3&contestProbId=AXxNn6GaPW4DFASZ&categoryId=AXxNn6GaPW4DFASZ&categoryType=CODE&problemTitle=&orderBy=RECOMMEND_COUNT&selectCodeLang=ALL&select-1=3&pageSize=10&pageIndex=3)
- 플랫폼: SWEA
- 난이도 : D3
- 시간 : 9ms
- 메모리 : 5,832kb
```
#include <numeric>
void solve() {
int day, result = 0; cin >> day;
int week[7]; int temp;
for (int i = 0; i < 7; i++) cin >> week[i];
int study_week = accumulate(week, week + 7, 0);
int answer = 9999999;
for (int change = 0; change < 7; change++)
{
if (week[0] == 1) {
if (day % study_week == 0) {
result = (day / study_week) * 7;
for (int i = 0; i < 7; i++) {
if (week[6 - i]) {
result -= i;
break;
}
}
}
else {
result = …
```

[Solved] : SWEA/13038

---

minwoo/SWEA/13038/sol.cpp

- 문제 : [SWEA 13038 교환학생](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AXxNn6GaPW4DFASZ)
- 플랫폼:  SWEA
- 난이도 : D3
- 시간 : 417ms
- 메모리 : 5832KB
```cpp
int TC;
const int DATE = 7;
int run(int n, char arr[], int idx) {
int d = 0, count = 0;
// 날짜 시작
while (n > count) {
if (arr[idx] == '1') count++;
// 요일 변경
idx = (idx + 1) % DATE;
d++;
}
return d;
}
int main() {
FILE* fp;
freopen_s(&fp, "input.txt", "r", stdin);
cin >> TC;
// 교환학생들을 위한 수업은 특정 요일에만 진행된다.
// 7개의 정수로 표현(a1, a2, ..., a7)
// 일요일에 교환학생을 위한 수업이 열리면 a1 = 1, 아니면 0
// 월요일에 교환학생을 위한 수업이 열리면 a2 = 1 아니면 0 ...
// 토요일은 a7
// 교환학생으로 n일동안 수업을 들으려고 한다.
// 목표를 이루기 위해 대학교에 지내야 하는 최소 일수
for (int t = 1; t <= TC; t++) {
int n;
char arr[DATE];
cin >> n;
for (int …
```

[Solve] : [SWEA] 13038 교환학생 - 문제 해결

---

Comet/BOJ/20055/sol.cpp

- 문제 : [컨베이어 벨트 위의 로봇문제 해결](https://www.acmicpc.net/problem/20055)
- 플랫폼: 백준
- 난이도 : 골드 5
- 시간 : 100ms
- 메모리 : 2024kb
```cpp
#include <deque>
void drop(deque<vector<int>>& conveyor, int down) {
conveyor[down][0] = 0;
}
int main() {
int length, limit; cin >> length >> limit;
deque<vector<int>> conveyor;
int input_temp;
for (int i = 0; i < length * 2; i++) {
cin >> input_temp;
conveyor.push_back({ 0, input_temp });
}
int up = 0, down = length - 1, is_robot = 0, durability = 1, cnt = 0;
int sycle = 0;
vector<int> temp;
// 내구도 0이 제한 이상이 되면 종료
while (cnt < limit)
{
sycle++;
// 컨베이어 한칸 이동
temp = conveyor.back(); conveyor.pop_back();
conveyor.push_front(temp);
// 로봇이 내리는곳 도착하면
if (conveyor[down][is_robot]) drop(conveyor, down);
//로봇 한칸씩 …
```

[Solved] BOJ/20055 컨베이어 벨트 위의 로봇문제 해결

---

Comet/BOJ/1146/sol.cpp

- 문제 : [지름길](https://www.acmicpc.net/problem/1446)
- 플랫폼: 백준
- 난이도 : 실버 1
- 시간 : 0ms
- 메모리 : 2024kb
```cpp
int result;
void solve() {
int num, length; cin >> num >> length;
vector<vector<int>> arr(num, vector<int>(3));
vector<int> dp(length + 1, 0 );
for (int i = 0; i < num; i++) {
cin >> arr[i][0] >> arr[i][1] >> arr[i][2];
}
sort(arr.begin(), arr.end(), [](const vector<int>& a, const vector<int>& b) { return a[1] < b[1]; });
arr.push_back({ -1, -1, -1 });
int pointer = 0;
for (int i = 1; i <= length; i++) {
if (arr[pointer][1] == i) {
dp[i] = min({ dp[i - 1] + 1, dp[arr[pointer][0]] + arr[pointer][2]});
pointer++;
while (arr[pointer][1] == i) {
dp[i] = min({ dp[i - 1] + 1, dp[arr[pointer][0]] + …
```

[Solved] : BOJ/1446 지름길 문제 해결

---

Comet/BOJ/4485/sol.cpp

- 문제 : [녹색 옷 입은 애가 젤다지?](https://www.acmicpc.net/problem/4485)
- 난이도 : 골드 5
- 시간 : 12ms
- 메모리 : 2156kb
```cpp
#include <utility>
int length, result, tc = 0;
int dy[4] = { 0, 0, 1, -1 };
int dx[4] = { 1, -1, 0, 0 };
void solve() {
vector<vector<int>> map(length, vector<int>(length));
vector<vector<int>> dijkstra(length, vector<int>(length, 999999999));
queue<pair<int, int>> que;
for (int i = 0; i < length; i++) {
for (int j = 0; j < length; j++) {
cin >> map[i][j];
}
}
dijkstra[0][0] = map[0][0];
que.push(make_pair(0, 0));
pair<int, int> current;
while (que.size() > 0)
{
current = que.front(); que.pop();
for (int i = 0; i < 4; i++) {
tempy = current.first + dy[i]; tempx …
```

[Solved] : BOJ/4485 녹색 옷 입은 애가 젤다지? 문제 해결

---

minwoo/BOJ/30702/sol.cpp
minwoo/BOJ/30702/sol.py

- 문제 : [BOJ 30702 국기 색칠하기](https://www.acmicpc.net/problem/30702)
- 플랫폼: 백준
- 난이도 : Gold 5
- 시간 : Python 64 ms / C++ 0 ms
- 메모리 : Python 35004 KB / C++ 2032 KB
<details>
```py
import sys
dxy = (1, 0), (0, 1), (-1, 0), (0, -1)
def bfs(sx, sy, color):
global A, visited
dq = deque([(sx, sy)])
coord = [(sx, sy)]
visited[sx][sy] = True
while dq:
x, y = dq.popleft()
if nx >= N or nx < 0 or ny >= M or ny < 0: continue
if visited[nx][ny] or A[nx][ny] != A[sx][sy]: continue
coord.append((nx, ny))
dq.append((nx, ny))
visited[nx][ny] = True
for x, y in coord:
A[x][y] = color
N, M = map(int, input().split())
A = [list(input().strip()) for _ in range(N)]
B = …
```

[Solve] : [BOJ] 30702 국기 색칠하기 - 문제 해결

---

Comet/BOJ/3190/sol.cpp

- 문제 : [뱀](https://www.acmicpc.net/problem/3190)
- 플랫폼: 백준
- 난이도 : 골드 4
- 시간 : 0ms
- 메모리 : 2024kb
```
const int apple = 1;
const int snake = 2;
int result = 0;
int length, num_apple, apple_y, apple_x, num_command, c_time, c_rotate, y = 0, x = 0;
int tempy, tempx, pointer = 0;
int dy[4] = { 0, 1, 0, -1 };
int dx[4] = { 1, 0, -1, 0 };
int turn_left[4] = { 3, 0, 1, 2 };
int turn_right[4] = { 1, 2, 3, 0 };
int direc = 0;
void solve() {
cin >> length >> num_apple;
vector<vector<int>> board(length, vector<int>(length, 0));
queue<pair<int, int>> que;
que.push(make_pair(y, x));
board[0][0] = snake;
pair<int, int> cur;
for (int i = 0; i < num_apple; i++) {
cin >> apple_y >> apple_x; board[apple_y - 1][apple_x - 1] = apple; …
```

[Solved] : BOJ/3190 뱀 문제해결

---

Comet/BOJ/14503/sol.cpp

- 문제 : [로봇청소기](https://www.acmicpc.net/problem/14503)
- 플랫폼: 백준
- 난이도 : 골드 5
- 시간 : 0ms
- 메모리 : 2020kb
```
int result = 0;
int  low, col;
int direc, y, x;
int dy[4] = { -1, 0, 1, 0 };
int dx[4] = { 0, 1, 0, -1 };
int rev[4] = { 2, 3, 0, 1 };
int rot[4] = { 3, 0, 1, 2 };
void solve() {
cin >> low >> col;
cin >> y >> x >> direc;
vector<vector<int>> arr(low, vector<int>(col, 0));
for (int i = 0; i < low; i++) {
for (int j = 0; j < col; j++) {
cin >> arr[i][j];
}
}
int flag = 0;
while (true)
{	
if (arr[y][x] == 0) {
arr[y][x] = 2; // ÇöÀç À§Ä¡ Ã»¼Ò
result++;
}
flag = 0;
for (int i = 0; i < 4; i++) {
tempy = y + dy[i]; tempx = x + dx[i];
if (tempy >= 0 && tempy < low && tempx >= 0 && tempx < col …
```

[Solved] : BOJ/14503 로봇청소기 문제해결

---

minwoo/BOJ/4485/sol.cpp
minwoo/BOJ/4485/sol.py

- 문제 : [BOJ 4485 녹색 옷 입은 애가 젤다지?](https://www.acmicpc.net/problem/4485)
- 플랫폼: 백준
- 난이도 : Gold 4
- 시간 : Python 72 ms / C++ 4 ms
- 메모리 : Python 35508 KB / C++ 2216 KB
<details>
```py
import sys
import heapq
INF = float('inf')
dxy = (1, 0), (0, 1), (-1, 0), (0, -1)
def dijkstra():
global N, grid
distance = [[INF] * N for _ in range(N)]
hq = []
heapq.heappush(hq, ((x := grid[0][0]), 0, 0))
distance[0][0] = x
while hq:
d, x, y = heapq.heappop(hq)
if d > distance[x][y]:
continue
if x == N-1 and y == N-1:
return d
if nx >= N or nx < 0 or ny >= N or ny < 0:
continue
if (k := distance[nx][ny]) != INF:
continue
if (acc := d + grid[nx][ny]) >= k:
continue
heapq.heappush(hq, (acc, nx, ny)) …
```

[Solve] : [BOJ] 4485 녹색 옷 입은 애가 젤다지? - 문제 해결

---

JJangDongHyeon/BOJ/16928/sol.py

- 문제 : 뱀과 사다리 게임
- 플랫폼: 백준
- 난이도 : 골드5
- 시간 : 60ms
- 메모리 : 35056KB
```
import sys
sys.stdin = open('input.txt')
ladder_num , snake_num = map(int, input().split())
jump_ladder_snake = dict()
for i in range(ladder_num + snake_num):
start, end = map(int, input().split())
jump_ladder_snake[start] = end
visited = [0] * 101 # 왜 보드칸은 100칸인데 101칸을 만드냐면, 인덱스 값을 숫자 그대로 쓰기 위해서임
queue = deque([(1, 0)]) # (현재 위치, 이동 횟수)
visited[1] = 1
while queue:
current, jump_count = queue.popleft()
if current == 100:
print(jump_count)
break
for dice in range(1, 7): # 주사위는 1부터 6까지 있기때문
next_pos = current + dice
if next_pos > 100:
continue
if next_pos in jump_ladder_snake:
next_pos = jump_ladder_snake[next_pos]
if not visited[next_pos]:
visited[next_pos] = True
queue.append((next_pos, …
```

[Solve] :뱀과 사다리 게임 문제 해결

---

minwoo/PGM/43162/sol.cpp

- 문제 : PGM 43162 네트워크
- 플랫폼: 프로그래머스
- 난이도 : Lv.3
```cpp
#include <deque>
void bfs(vector<vector<int>>& comp, vector<bool>& visited, int stv, int n) {
deque<int> dq;
dq.push_back(stv);
visited[stv] = true;
while (!dq.empty()) {
int vtx = dq.front(); dq.pop_front();
for (int adj = 0; adj < n; adj++) {
if (visited[adj] || vtx == adj || comp[vtx][adj] == 0) continue;
dq.push_back(adj);
visited[adj] = true;
}
}
}
int solution(int n, vector<vector<int>> computers) {
int answer = 0;
vector<bool> visited(n);
for (int i = 0; i < n; i++) {
if (visited[i]) continue;
bfs(computers, visited, i, n);
answer++;
}
return answer;
}
```
- BFS로 문제 해결
- 방문하지 않은 컴퓨터는 같은 네트워크상에 없으므로 순회를 통해 어떤 컴퓨터들이 같은 네트워크를 공유하는지 확인
- 모든 컴퓨터(정점)에서 이동 가능한 컴퓨터를 순회하면서 방문처리
- …

[Solve] : [PGM] 43162 네트워크 - 문제 해결

---

minwoo/BOJ/18405/sol.cpp

- 문제 : [BOJ 18405 경쟁적 전염](https://www.acmicpc.net/problem/18405)
- 플랫폼: 백준
- 난이도 : Gold 5
- 시간 : 116ms
- 메모리 : 2424KB
```cpp
#include <unordered_map>
int N, K, S, X, Y;
int dx[4] = { 0, 1, 0, -1 };
int dy[4] = { 1, 0, -1, 0 };
struct XY { int x; int y; };
void bfs(vector<vector<int>>& grid, vector<XY>& vq, int num) {
vector<XY> moving_virus;
for (int i = 0; i < vq.size(); i++) {
int x = vq[i].x, y = vq[i].y;
for (int d = 0; d < 4; d++) {
int nx = x + dx[d], ny = y + dy[d];
if (nx >= N || nx < 0 || ny >= N || ny < 0 || grid[nx][ny] != 0) continue;
grid[nx][ny] = num;
moving_virus.push_back({ nx, ny });
}
}
vq = moving_virus;
}
int main()
{
cin >> N >> K;
unordered_map<int, …
```

[Solve] : [BOJ] 18405 경쟁적 전염 - 문제 해결

---

minwoo/BOJ/19238/sol.py

- 문제 : [BOJ19238 스타트 택시](https://www.acmicpc.net/problem/19238)
- 플랫폼: 백준
- 난이도 : Gold 2
- 시간 : 136ms
- 메모리 : 35132 KB
```py
import sys
dxy = (1, 0), (0, 1), (-1, 0), (0, -1)
def search_passenger():
global grid, now_x, now_y, dxy, N
if (c := grid[now_x][now_y]) != 0:
grid[now_x][now_y] = 0
return c, 0
visited = [[0] * N for _ in range(N)]
dq = deque([(now_x, now_y, 0)])
visited[now_x][now_y] = 1
pas = []
is_flag = -1
while dq:
x, y, dist = dq.popleft()
if (c := grid[x][y]) != 0:
if is_flag < 0: is_flag = dist
if is_flag == dist:
pas.append((dist, x, y, c))
if -1 < is_flag < dist:
break
if nx >= N or nx < 0 or ny >= N or ny < 0:
continue
if visited[nx][ny] == 1 or grid[nx][ny] == 1: continue …
```

[Solve] : [BOJ] 19238 스타트 택시 - 문제 해결

---

JJangDongHyeon/BOJ/16928/sol.py
JJangDongHyeon/BOJ/9205/sol.py

- 문제 : 맥주 마시면서 걸어가기
- 플랫폼: 백준
- 난이도 : 골드 5
- 시간 : 120ms
- 메모리 : 34952kb
```
T = int(input())
for tc in range(1, T + 1):
convinience_num = int(input())
que = deque()
coor = []
for _ in range(convinience_num + 2):
x, y = map(int, input().split())
coor.append((x,y))
visited = [0] * len(coor)
visited[0] = 1
que.append(coor[0])
end_x, end_y = coor.pop()
while que:
x, y = que.popleft()
x_sum , y_sum = abs(end_x - x) , abs(end_y - y)
if x_sum + y_sum <= 1000:
print('happy')
break
for i in range(1, len(coor)):
if visited[i]: continue
convinience_x, convinience_y = coor[i][0], coor[i][1]
x_sum, y_sum = abs(convinience_x - x) , abs(convinience_y - y)
if x_sum + y_sum <= 1000:
visited[i] = 1
que.append((convinience_x, convinience_y))
else:
print('sad')
```
일단 도착점만 따로 …

[Solve] :맥주 마시면서 걸어가기 문제 해결

---

minwoo/BOJ/1520/sol.py

- 문제 : [BOJ 1520 내리막 길](https://www.acmicpc.net/problem/1520)
- 플랫폼: 백준
- 난이도 : Gold 3
- 시간 : 112ms
- 메모리 : 46104KB
```py
import sys
sys.setrecursionlimit(10**6)
dxy = (1, 0), (0, 1), (-1, 0), (0, -1)
def dfs(x, y):
global dp, grid, end_xy
if (x, y) == end_xy:
return 1
if dp[x][y] != -1:
return dp[x][y]
dp[x][y] = 0
if nx >= M or nx < 0 or ny >= N or ny < 0:
continue
if grid[nx][ny] < grid[x][y]:
dp[x][y] += dfs(nx, ny)
return dp[x][y]
M, N = map(int, input().split())
grid = [list(map(int, input().split())) for _ in range(M)]
dp = [[-1] * N for _ in range(M)]
start_xy = (0, 0)
end_xy = (M-1, N-1)
print(dfs(*start_xy))
```
- GPT랑 학습했습니다.
- 도착지라면 return 1(dfs(x, y)를 호출한 결과로 +1 할 수 있도록 하기 위해서)
- 메모이제이션으로 이미 가던 길이라면 그대로 반환 …

[Solve] : [BOJ] 1520 내리막 길 - 문제 해결

---

Comet/BOJ/18405/sol.cpp

- 문제 : [경쟁적 전염](https://www.acmicpc.net/problem/18405)
- 플랫폼: 백준 
- 난이도 : 골드 5
- 시간 : 124ms
- 메모리 : 2424kb
```
#include <unordered_map>
struct yx
{
int y, x;
};
int length, num;
int sec, targety, targetx;
unordered_map<int, vector<yx>> dict;
int time, tempy, tempx;
int dy[4] = { 0, 0, -1, 1 };
int dx[4] = { -1, 1, 0, 0 };
yx cur;
void delta(vector<vector<int>>& arr, vector<yx>& vec,int val) {
vector<yx> memo;
int len = vec.size();
for (int i = 0; i < len; i++) {
cur = vec[i];
for (int j = 0; j < 4; j++) {
tempy = cur.y + dy[j]; tempx = cur.x + dx[j];
if (tempy >= 0 && tempy < length && tempx >= 0 && tempx < length && arr[tempy][tempx] == 0) {
memo.push_back({ tempy, tempx });
arr[tempy][tempx] = val;
}
}
}
vec = memo;
}
void …
```

[Solved] : BOJ/18405 경쟁적 전염 문제 해결

---

minwoo/BOJ/15686/sol.cpp
minwoo/BOJ/15686/sol.py

- 문제 : [BOJ 15686 치킨 배달](https://www.acmicpc.net/problem/15686)
- 플랫폼: 백준
- 난이도 : Gold 5
- 시간 : Python 128ms / C++ 4ms
- 메모리 : Python 32412KB / C++ 2024KB
<details>
```py
import sys
INF = 1e9
def dfs(depth, dist, index):
global res
if depth == M:
res = min(res, sum(dist))
return
for i in range(index + 1, store_size):
next_dist = dist[::]
x, y = store[i]
for idx, rc in enumerate(home):
r, c = rc
now = abs(x - r) + abs(y - c)
if next_dist[idx] <= now: continue
next_dist[idx] = now
dfs(depth+1, next_dist, i)
N, M = map(int, input().split())
store, home = [], []
grid = []
for i in range(N):
temp = list(map(int, input().split()))
grid.append(temp)
for j in range(N):
if temp[j] == 1:
home.append((i, j))
elif temp[j] == 2:
store.append((i, j)) …
```

[Solve] : [BOJ] 15686 치킨 배달 - 문제 해결

---

JJangDongHyeon/BOJ/14889/sol.py

- 문제 : 스타트와 링크
- 플랫폼: 백준 
- 난이도 : 실버 1
- 시간 : 1748ms
- 메모리 : 32412kb
```
def comb(idx, selected):
if len(selected) == one_team_count:
global min_synergy
if 0 not in selected: return #중복 제거
a_team = selected
b_team = [i for i in range(person_count) if i not in a_team]
a_synergy, b_synergy = get_synergy(a_team), get_synergy(b_team)
final_synergy = abs(a_synergy - b_synergy)
min_synergy = min(min_synergy, final_synergy)
for i in range(idx, person_count):
comb(i + 1, selected + [i])
def get_synergy(team):
synergy = 0
for i in range(len(team)):
for j in range(len(team)):
if i == j : continue
synergy += board[team[i]][team[j]]
return synergy
person_count = int(input())
one_team_count = person_count // 2
board = [list(map(int, input().split())) for _ in range(person_count)]
min_synergy = …
```

[Solve] :스타트와 링크 문제 해결

---

Comet/BOJ/14889/sol.cpp

- 문제 : [스타트와 링크](https://www.acmicpc.net/problem/14889)
- 난이도 : 실버 1
- 시간 : 112ms
- 메모리 : 2024kb
```
#include <cmath>
int num, result = 9999999, limit;
vector<vector<int>> arr(20, vector<int>(20));
bool visited[20] = { 0 };
void calculate() {
int start = 0, link = 0, diff;
vector<int> startteam, linkteam;
for (int i = 0; i < num; i++) {
if (visited[i]) {
startteam.push_back(i);
}
else {
linkteam.push_back(i);
}
}
for (int i = 0; i < startteam.size(); i++) {
for (int j = i + 1; j < startteam.size(); j++) {
start += arr[startteam[i]][startteam[j]]; start += arr[startteam[j]][startteam[i]];
}
}
for (int i = 0; i < linkteam.size(); i++) {
for (int j = i + 1; j < linkteam.size(); j++) {
link += …
```

[Solved] : BOJ/14889 스타트와 링크 문제해결

---

Comet/BOJ/1245/sol.cpp

- 문제 : [농장관리](https://www.acmicpc.net/problem/1245)
- 난이도 : 골드 5
- 시간 : 0ms
- 메모리 : 2060kb
```cpp
#include <cstring>
int result = 0, row, col;
int arr[100][70];
bool visited[100][70];
bool search[100][70];
struct yx
{
int y, x;
};
vector<yx> direc = { {-1, -1}, {-1, 0}, {-1, 1}, {0, -1}, {0, 1}, {1, -1}, {1, 0}, {1, 1} };
int min(int a, int b) {
if (a > b) {
return a;
}
else
{
return b;
}
}
bool dfs(int y, int x) {
bool flag = 1;
search[y][x] = 1;
for (int i = 0; i < 8; i++) {
tempy = y + direc[i].y; tempx = x + direc[i].x;
if (tempy >= 0 && tempy < row && tempx >= 0 && tempx < col && !visited[tempy][tempx]) {
if (arr[tempy][tempx] == arr[y][x]) {
visited[y][x] = 1;
flag = …
```

[Solved] : BOJ/1245 농장 관리 문제 해결

---

Comet/Programmers/43162/sol.cpp

- 문제 : [네트워크](https://school.programmers.co.kr/learn/courses/30/lessons/43162)
- 플랫폼:  프로그래머스
- 난이도 : 모름
- 시간 : 최대 시간 0.08ms
- 메모리 : 최대 4.42mb
```
@@ -0,0 +1,27 @@
void bfs(vector<vector<int>> computers, vector<bool>& visited, int num, int n){
queue<int> que; que.push(num); int cur; visited[num] = 1;
while (!que.empty()){
cur = que.front(); que.pop();
for (int i = 0; i < n; i++){
if (computers[cur][i] && !visited[i]){
visited[i] = 1;
que.push(i);
}
}
}
}
int solution(int n, vector<vector<int>> computers) {
int answer = 0;
vector<bool> visited(n, 0);
for (int i = 0; i < n; i++){
if (visited[i] == 0){
bfs(computers, visited, i, n);
answer++;
}
}
return answer;
}
```
* bfs로 그래프 탐색
---

[Solved] : Programmers/43162 네트워크 문제 해결

---

Comet/BOJ/1374/sol.cpp

- 문제 : [강의실](https://www.acmicpc.net/problem/1374)
- 플랫폼: 백준 
- 난이도 : 골드 5
- 시간 : 44ms
- 메모리 : 3704kb
```
struct Meeting {
int start, end;
};
int main() {
ios::sync_with_stdio(false);
cin.tie(NULL);
int num;
cin >> num;
vector<Meeting> meetings(num);
for (int i = 0; i < num; i++) {
int n;
cin >> n >> meetings[i].start >> meetings[i].end;
}
sort(meetings.begin(), meetings.end(), [](const Meeting& a, const Meeting& b) {
return a.start < b.start;
});
priority_queue<int, vector<int>, greater<int>> min_heap;
min_heap.push(meetings[0].end);
for (int i = 1; i < num; i++) {
if (min_heap.top() <= meetings[i].start) {
min_heap.pop();
}
min_heap.push(meetings[i].end);
}
cout << min_heap.size() << '\n'; …
```

[Solved] : BOJ/1374 강의실 문제 해결

---

JJangDongHyeon/BOJ/1374/sol.py

- 문제 : 강의실 
- 플랫폼: 백준 
- 난이도 : 골드5
- 시간 : 2732ms, 308ms (readline으로 받느냐 마느냐 차이)
- 메모리 : 48580kb
```python
#import sys
#sys.stdin = open('input.txt')
#import heapq
import heapq
import sys
room_number = int(input())
room_info = []
for i in range(room_number):
class_num , class_start_time, class_end_time = map(int,input().split())
room_info.append((class_start_time, class_end_time))
room_info.sort()
heap = [room_info[0][1]]  # 첫 번째 강의의 종료 시간 미리 넣기
for i in range(1, len(room_info)):  # 두 번째 강의부터 반복
start, end = room_info[i]
if heap[0] <= start:
heapq.heappop(heap)
heapq.heappush(heap, end)
print(len(heap))
```
---
1. 일단 시작 시간을 기준으로 오름차 정렬을 해요. 맨 처음ㅇ ㅔ튜플을 시작 시간을 먼저 넣어서, .sort(key=lambda x: x[0])를 할 필요는 없었네요.
2. 그리고 힙큐를 이용해서 가장 빨리 사용되는 강의실의 종료 시간을 힙큐에 넣어요
3. 파이썬 힙큐의 맨 …

[Solve] :강의실 문제 해결

---

Comet/BOJ/9251/sol.cpp

- 문제 : [LCS](https://www.acmicpc.net/problem/9251)
- 플랫폼: 백준
- 난이도 : 골드 5
- 시간 : 4ms
- 메모리 : 5984kb
```cpp
string s1 = "ABCBDAB";
string s2 = "BDCAB";
int main() {
s1 = '.' + s1; s2 = '.' + s2;
int len1 = s1.length();
int len2 = s2.length();
vector<vector<int>> dp(len1, vector<int>(len2, 0));
for (int i = 1; i < len1; i++) {
for (int j = 1; j < len2; j++) {
if (s1[i] == s2[j]) {
dp[i][j] = dp[i - 1][j - 1] + 1;
}
else
{
dp[i][j] = max(dp[i - 1][j], dp[i][j - 1]);
}
}
}
cout << dp[len1 - 1][len2 - 1] << '\n';
return 0;
}
```
* 2차원 dp 배열을 만들어.
* 문자열 1과 2를 하나씩 2중 포문으로 비교하는데, 만약 같다면 i - 1, j - 1(이전의 최대 길이) 에서 1추가해서 대입.
* 만약 다르면, 그냥 [i][j - 1] (현재 비교완료한 데이터중 가장 큰 길이) [i - 1][j] (이전꺼에서 비교한 데이터) 중 …

[Solved] : BOJ/9251 LCS 문제 해결

---

Comet/BOJ/20926/sol.cpp

- 문제 : [얼음 미로](https://www.acmicpc.net/problem/20926)
- 플랫폼: 백준 
- 난이도 : 골드 2
- 시간 : 24ms
- 메모리 : 3480kb
```
#include <climits>
vector<string> arr;
int row, col;
const char target = 'E';
const char tera = 'T';
const char hole = 'H';
const char rock = 'R';
int dy[4] = { 0, 0, -1, 1 };
int dx[4] = { -1, 1, 0, 0 };
struct yx
{
int y, x, time;
};
struct compare {
bool operator()(const yx& a, const yx& b) {
return a.time > b.time;
}
};
yx startPoint, endPoint;
//시작점 끝점 찾기
void find_start() {
for (int i = 0; i < row; ++i)
{
for (int j = 0; j < col; ++j)
{
if (arr[i][j] == tera) {
startPoint = { i, j, 0 };
}
else if (arr[i][j] == target) {
endPoint = { i, j, 0 };
}
}
}
}
//다익스트라
int dijk(yx& start, yx& …
```

[Solved] : BOJ/20926 얼음미로 문제 해결

---

minsun/BOJ/13699/sol.py
minsun/BOJ/9205/sol.py

- 문제 : [점화식](https://www.acmicpc.net/problem/13699)
- 플랫폼: 백준
- 난이도 : 실버4
- 시간 : 36ms
- 메모리 : 32412KB
```py
n = int(input())
dp = [0] * (n + 1)
dp[0] = 1
for i in range(1, n + 1):
total = 0
for j in range(i):
total += dp[j] * dp[i - 1 - j]
dp[i] = total
print(dp[n])
```
- 점화식 .. 이건 미친놈입니다... 손으로 계산해보고 ... 수학을 다시 공부해야할까요 그나마 힌트가 있어서 다행이엇듬
---

[Solve] : [BOJ] 13699 점화식 - 문제 해결

---

minwoo/BOJ/20926/sol.cpp
minwoo/BOJ/20926/sol.py

- 문제 : [BOJ 20926 엄음 미로](https://www.acmicpc.net/problem/20926)
- 플랫폼: 백준
- 난이도 : Gold 2
- 시간 : Python 492ms / C++ 16ms
- 메모리 : Python 39444KB / C++ 3348KB
<details>
```py
import sys
import heapq
INF = float('inf')
dxy = (0, 1), (1, 0), (0, -1), (-1, 0)
class Coord:
def __init__(self):
self.x = None
self.y = None
def dijkstra():
global grid, W, H
hq = [(0, st.x, st.y)]
distance = [[INF] * W for _ in range(H)]
distance[st.x][st.y] = 0
while hq:
dist, x, y = heapq.heappop(hq)
if dist > distance[x][y]: continue
w = 0
while True:
if nx >= H or nx < 0 or ny >= W or ny < 0: break
if (now := grid[nx][ny]) == 'H' or distance[nx][ny] <= (acc := dist + w): break
elif now == 'R':
nx -= dx
ny -= dy
if (nx, …
```

[Solve] : [BOJ] 20926 엄음 미로 -  문제 해결

---

Comet/BOJ/9080/sol.cpp

- 문제 : [PC방 요금](https://www.acmicpc.net/problem/9080)
- 플랫폼: 백준
- 난이도 : 골드 4
- 시간 : 0ms
- 메모리 : 2024kb
```
void solve() {
string time; cin >> time;
int cost = 0, len; cin >> len;
int hour, min;
hour = (time[0] - '0') * 10 + (time[1] - '0');
min = (time[3] - '0') * 10 + (time[4] - '0');
int cur = hour * 60 + min + 120;
while (len > 0)
{
int spend;
cur = cur % 1440;
if (cur >= 600 && cur <= 1439) {	// 8시에서 22시 사이면.
spend = (len < (1440 - cur)) ? len : (1440 - cur);
cost += spend / 60 + (spend % 60 == 0 ? 0 : 1);
len -= spend + (spend % 60 == 0 ? 0 : 60 - spend % 60);
cur += spend + (spend % 60 == 0 ? 0 : 60 - spend % 60);
}
else {
if (len / 60 >= 5 && cur <= 300) {	// 정액권을 쓰는게 이득이면.
cost += 5;
spend = 600 - cur; …
```

[Solved] : BOJ/9080 PC방 요금 문제 해결

---

minsun/BOJ/25328/sol.py

- 문제 :  문자열 집합 조합하기
- 플랫폼: 백준
- 난이도 :  실버2  
- 시간 : 148ms. 
- 메모리 : 45708KB
``` py
from itertools import combinations
def make_combi_set(s, k):
return set(''.join(c) for c in combinations(s, k))
X = input().strip()
Y = input().strip()
Z = input().strip()
k = int(input())
x_combi = make_combi_set(X, k)
y_combi = make_combi_set(Y, k)
z_combi = make_combi_set(Z, k)
all = list(x_combi) + list(y_combi) + list(z_combi)
count = {}
for c in all:
if c in count:
count[c] += 1
else:
count[c] = 1
result = sorted([c for c in count if count[c] >= 2])
if result:
for r in result:
print(r)
else:
print(-1)
```
-  조합이라는  단어 ..  그것을  보면 이터툴즈.... 만  떠올리면 안 되는데 ... 
---

[Solve] : [BOJ] 25328 - 문자열 집합 조합하기 문제 해결

---

minwoo/BOJ/9080/sol.py

- 문제 : [BOJ 9080 PC방 요금](https://www.acmicpc.net/problem/9080)
- 플랫폼: 백준
- 난이도 : Gold 4
- 시간 : 32ms
- 메모리 : 32412KB
```py
T = int(input())
for t in range(T):
HHMM, time = input().split()
h, m = map(int, HHMM.split(':'))
time = int(time)
fee = 0
while time > 0:
rh, rm = (h+2) % 24, m
rotated_min = rh * 60 + rm
if 0 <= rh <= 4 and time > 300:
jump = 600 - rotated_min
fee += 5000
time -= jump
h, m = 8, 0
else:
fee += 1000
time -= 60
h = (h + 1) % 24
print(fee)
```
- 어렵네요
---

[Solve] : [BOJ] 9080 PC방 요금 -  문제 해결

---

Comet/BOJ/1943/sol.cpp

- 문제 : [동전 분배](https://www.acmicpc.net/problem/1943)
- 플랫폼: 백준 
- 난이도 : 골드 2
- 시간 : 16ms
- 메모리 : 2468kb
```
#include <cstring>
int coins[100];
int nums[100];
bool dp[50001];
int memo[50001];
void solve() {
memset(dp, 0, sizeof(dp));
int N; cin >> N;
int target = 0;
for (int i = 0; i < N; ++i) {
cin >> coins[i]; cin >> nums[i];
target += coins[i] * nums[i];
}
if (target % 2 == 1) {
cout << 0 << '\n';
return;
}
dp[0] = 1;
target /= 2;
int coin;
int num;
int diff;
for (int i = 0; i <= N; ++i) {
coin = coins[i];
num = nums[i];
vector<int> memo(target + 1, 0);
for (int k = coin; k <= target; ++k) {
if (dp[k]) {
continue;
}
diff = k - coin;
if (dp[diff] == 1 && memo[diff] < num) {
dp[k] = 1;
memo[k] = memo[diff] + 1;
}
}
}
if …
```

[Solved] : BOJ/1943 동전 분배 문제 해결

---

minwoo/BOJ/2740/sol.cpp

- 문제 : [BOJ 2740 행렬곱셈](https://www.acmicpc.net/problem/2740)
- 플랫폼: 백준
- 난이도 : Silver 5
- 시간 : 0ms
- 메모리 : 2156KB
```cpp
int N, M, K;
void input(vector<vector<int>>& array, int n, int m) {
for (int i = 0; i < n; i++)
for (int j = 0; j < m; j++)
cin >> array[i][j];
return;
}
void run(
vector<vector<int>>& a,
vector<vector<int>>& b) {
for (int n = 0; n < N; n++) {
for (int k = 0; k < K; k++) {
int temp = 0;
for (int m = 0; m < M; m++)
temp += a[n][m] * b[m][k];
cout << temp << (k == K - 1 ? "\n" : " ");
}
}
return;
}
void solve() {
cin >> N >> M;
vector<vector<int>> A(N, vector<int>(M));
input(A, N, M);
cin >> M >> K;
vector<vector<int>> B(M, vector<int>(K));
input(B, M, K);
run(A, B);
return;
}
int main() { …
```

[Solve] : [BOJ] 2740 행렬 곱셈 -  문제 해결

---

minwoo/BOJ/30191/sol.cpp

- 문제 : [문자열 만들기 1](https://www.acmicpc.net/problem/30191)
- 플랫폼: 백준
- 난이도 : Gold 4
- 시간 : 16ms
- 메모리 : 7280KB
```cpp
int N, K;
void solve() {
string grade;
cin >> N >> grade;
vector<char> arr;
string cmd;
for (int i = grade.size() - 1; i > -1; i--) {
bool flag = 0;	
if (!arr.empty() && grade[i] == arr.back()) {
arr.pop_back();
cmd.push_back('N');
continue;
}
if (grade[i] == 'U') {
cmd.push_back('S');
arr.push_back('S');
}
else {
cmd.push_back('U');
arr.push_back('U');
}
cmd.push_back('N');
}
cout << cmd.size() << "\n" << cmd << "\n";
return;
}
int main() {
solve();
return 0;
}
```
- 뒤에서 한칸씩 당겨오면서 확인합니다.
- 역순으로 확인하기 때문에 U를 확인하면 SU를, S를 확인하면 US를 삽입한다고 명령어에 …

[Solve] : [BOJ] 30191 문자열 만들기 1 - 문제 해결

---

minsun/BOJ/2217/sol.py

- 문제 : [로프](https://www.acmicpc.net/problem/2217)
- 플랫폼: 백준 
- 난이도 : 실버4
- 시간 : 2516ms
- 메모리 : 36264KB
```
N = int(input())
rope = [int(input()) for _ in range(N)]
rope.sort()
max_weight = 0
for i in range(N):
weight = rope[i] * (N - i)
max_weight = max(max_weight, weight)
print(max_weight)
```
- 아니 시간 꿈인가 .. 
---

[Solve] : [BOJ] 2217 - 로프 문제 해결

---

minwoo/BOJ/2757/sol.cpp

- 문제 : [엑셀](https://www.acmicpc.net/problem/2757)
- 플랫폼: 백준
- 난이도 : 실버 3
- 시간 : 0ms
- 메모리 : 2024KB
```cpp
bool endpoint = true;
pair<int, int> get_input() {
int r = 0, c = 0;
string input;
getline(cin, input);
int n = input.size();
int digits = 1;
while (isdigit(input[--n])) {
c += (input[n] - '0') * digits;
digits *= 10;
}
digits = 1;
while (isdigit(input[--n])) {
r += (input[n] - '0') * digits;
digits *= 10;
}
return { r, c };
}
string to_26(int n) {
string res;
while (n > 0) {
res = char((--n % 26) + 'A') + res;
n /= 26;
}
return res;
}
void solve() {
auto [row, col] = get_input();
if (row == 0 && col == 0) {
endpoint = false;
return;
}
string c = to_26(col);
cout << c << row << "\n";
return;
}
int main() { …
```

[Solve] : [BOJ] 2757 엑셀 - 문제 해결

---

Comet/SWEA/1849/sol.cpp

- 문제 : [영준이의 무게측정](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5LeQJqDpwDFAXc)
- 플랫폼: SWEA
- 난이도 : d6
- 시간 : 400 ms
- 메모리 : 17,704 kb
```cpp
int num, questions;
int parents[1000001];
int diffs[1000001];
int ranks[1000001];
int a, b, diff;
int getParent(int a) {
if (parents[a] == a) return a;
int p = parents[a];
parents[a] = getParent(p);
diffs[a] += diffs[p];
return parents[a];
}
void joins(int a, int b, int diff) {
int pa = getParent(a);
int pb = getParent(b);
if (pa == pb) {
return;
}
if (ranks[pa] < ranks[pb]) {
parents[pa] = pb;
diffs[pa] = diffs[b] - diffs[a] + diff;
}
else {
parents[pb] = pa;
diffs[pb] = diffs[a] - diffs[b] - diff;
if (ranks[pb] == ranks[pa]) {
ranks[pa]++;
}
}
}
void …
```

[Solved] : SWEA/1849 영준이의 무게측정 문제 해결

---

minwoo/BOJ/17276/sol.cpp

- 문제 : [배열 돌리기](https://www.acmicpc.net/problem/17276)
- 플랫폼: 백준
- 난이도 : Silver 1
- 시간 : 192ms
- 메모리 : 3068KB
```cpp
int n, d;
void cw(vector<vector<int>>& v) {
vector<int> main_diag(n);
vector<int> sub_diag(n);
vector<int> mid_row(n);
vector<int> mid_col(n);
int j = ((n + 1) / 2) - 1;
for (int i = 0; i < n; i++) {
main_diag[i] = v[i][i];
sub_diag[i] = v[i][n - 1 - i];
mid_col[i] = v[i][j];
mid_row[i] = v[j][i];
}
for (int i = 0; i < n; i++) {
v[i][j] = main_diag[i]; // 세로 <- 주 대각
v[i][i] = mid_row[i];	// 주 대각 <- 가로
v[j][i] = sub_diag[n - 1 - i];	// 가로 <- 부 대각(끝부터 역순으로)
v[i][n - 1 - i] = mid_col[i];	// 부 대각 <- 세로
}
return;
}
void ccw(vector<vector<int>>& v) {
vector<int> main_diag(n);
vector<int> sub_diag(n);
vector<int> …
```

[Solve] : [BOJ] 17276 배열 돌리기 - 문제 해결

---

minsun/BOJ/12887/sol.py

- 문제 : [경로게임](https://www.acmicpc.net/problem/12887)
- 플랫폼: 백준 
- 난이도 : 골드5
- 시간 : 60ms
- 메모리 : 35108KB
``` py
import sys
sys.stdin = open('input.txt', 'r')
dxs = [0, 0, -1, 1]
dys = [1, -1, 0, 0]
N = int(input())
game_map = [list(map(str, input().strip())) for _ in range(2)]
visited = [[0] * N for _ in range(2)]
white = 0
for x in range(2):
for y in range(N):
if game_map[x][y] == '.':
white += 1
queue = deque()
for i in range(2):
if game_map[i][0] == '.':
queue.append((i, 0, 1))
visited[i][0] = 1
min_cnt = 9999999999
while queue:
x, y, cnt = queue.popleft()
if y == N-1:
min_cnt = min(min_cnt, cnt)
continue
for dx, dy in zip(dxs, dys):
nx = dx + x
ny = dy + y
if 0 <= nx < 2 and 0 <= ny < N:
if visited[nx][ny] != 1 and game_map[nx][ny] == '.': …
```

[Solve] : [BOJ] 12887 경로 게임 - 문제 해결

---

Comet/BOJ/12887/sol.cpp

- 문제 : [경로 게임](https://www.acmicpc.net/problem/12887)
- 플랫폼: 백준
- 난이도 : 골드 5
- 시간 : 0ms
- 메모리 : 2024kb
```cpp
#include <deque>
struct yx
{
int y, x, length;
};
int dy[3] = { 0,-1, 1 };
int dx[3] = { 1, 0, 0 };
int solve() {
int row = 2, col; cin >> col;
int cnt = col * 2;
vector<string> arr(row);
int visited[2][50] = { 0 };
for (int i = 0; i < row; ++i) {
cin >> arr[i];
for (auto& ch : arr[i]) {
if (ch == '#') cnt--;
}
}
deque<yx> que; 
if (arr[0][0] == '.') {
que.push_back({ 0, 0, 1 });
visited[0][0] = 1;
}
if (arr[1][0] == '.') {
que.push_back({ 1, 0, 1 });
visited[1][0] = 1;
}
yx cur;
while (!que.empty())
{
cur = que.front(); que.pop_front();
if (cur.x == col - 1) {
return cnt - cur.length;
} …
```

[Solved] : BOJ/12887 경로 게임 문제 해결

---

minwoo/BOJ/22891/sol.cpp
minwoo/BOJ/22891/sol.py

- 문제 : [휴먼 파이프라인](https://www.acmicpc.net/problem/22981)
- 플랫폼: 백준
- 난이도 : Gold 5
- 시간 : C++ 36ms / Python 256ms
- 메모리 : C++ 3584KB / Python 56452KB
<details>
```py
import sys
n, k = map(int, input().split())
v = sorted(list(map(int, input().split())))
res = 1e18
for i in range(1, n):
team = (v[0] * i) + (v[i] * (n-i))
c = (k // team) + (0 if k % team == 0 else 1)
res = min(res, c)
print(res)
```
</details>
<details>
<summary>C++</summary>
```cpp
/* 
두 팀으로 나눠져서 작업을 진행
두 팀 도우 적어도 한명은 포함되야 함
두 팀이 같은 수의 상자를 옮길 필요는 없음
팀 작업 속도 = (해당 팀에 속한 사람들의 작업속도 중 가장 느린 작업속도) x (팀에 속한 사람 수)
*/
long long n, k;
int main() {
ios::sync_with_stdio(false); cin.tie(NULL); …
```

[Solve] : [BOJ] 22891 휴먼 파이프라인 - 문제 해결

---

Comet/BOJ/31410/sol.cpp

- 문제 : [제독 작전](https://www.acmicpc.net/problem/31410)
- 플랫폼: 백준 
- 난이도 : 골드 3
- 시간 : 124ms
- 메모리 : 3588kb
```cpp
#include <climits>
struct dataset
{
long long loc, degree;
};
bool compare(const dataset& a, const dataset& b) {
return a.loc < b.loc;
}
int main() {
long long num, loc, degree;
long long Ltotal = 0, Rtotal = 0;
cin >> num;
vector<dataset> arr(num);
cin >> loc >> degree;
arr[i] = { loc, degree };
}
sort(arr.begin(), arr.end(), compare);
for (int i = 1; i < num; ++i) {
Ltotal += (arr[i].loc - arr[i - 1].loc) * i;
Rtotal += (arr[i].loc - arr[i - 1].loc) * (num - i);
}
Ltotal += arr[i].degree;
Rtotal += arr[i].degree;
}
long long result = …
```

[Solved] : BOJ/31410 제독 작전 문제 해결

---

Comet/BOJ/16932/sol.cpp

- 문제 : [모양 만들기](https://www.acmicpc.net/problem/16932)
- 플랫폼: 백준
- 난이도 : 골드 3
- 시간 : 264ms
- 메모리 : 14724kb
```cpp
#include <deque>
#include <unordered_set>
int arr[1000][1000];
int mapping[1000][1000];
bool visited[1000][1000];
int shape[1000000] = { 0 };
int dy[4] = { 0, 0, -1, 1 };
int dx[4] = { -1, 1, 0, 0 };
int row, col, idx = 0;
struct dataset
{
int y, x;
};
deque<dataset> que;
void bfs(int y, int x) {
que.clear();
que.push_back({ y, x });
int tempy, tempx, val = 0;
dataset cur;
visited[y][x] = 1;
val++;
idx++;
mapping[y][x] = idx;
while (!que.empty())
{
cur = que.front(); que.pop_front();
for (int i = 0; i < 4; ++i) {
tempy = cur.y + dy[i]; tempx = cur.x + dx[i];
if (tempy < 0 || tempy >= row || tempx < 0 || tempx >= col …
```

[Solved] : BOJ/16932 모양 만들기 문제 해결

---

Comet/BOJ/24053/소스.cpp

- 문제 : [알고리즘 수업 - 삽입 정렬 3](https://www.acmicpc.net/problem/24053)
- 플랫폼: 백준
- 난이도 : 골드 5
- 시간 : 0ms
- 메모리 : 2020kb
```cpp
int num;
vector<int> a;
vector<int> b;
bool find() {
if (a[i] != b[i]) return 0;
}
return 1;
}
int main() {
cin >> num;
a.resize(num);
b.resize(num);
cin >> a[i];
}
cin >> b[i];
}
int loc, cur;
for (int i = 1; i < num; ++i) {
loc = i - 1;
cur = a[i];
while (loc >= 0)
{
if (a[loc] > cur) {
a[loc + 1] = a[loc];
}
else {
break;
}
if (find()) {
cout << 1 << '\n';
return 0;
}
loc--;
}
if (loc + 1 != i) {
a[loc + 1] = cur;
}
}
cout << 0 << '\n';
return 0;
}
```
* 이론상 시간복잡도 1만 * 1만 * 1만 이라 무조건 시간초과인데 이게 왜 되는걸까유...
* 심지어 …

[Solved] : 알고리즘 수업 - 삽입 정렬 3  문제 해결

---

minwoo/BOJ/18511/sol.cpp

- 문제 : [큰 수 구성하기](https://www.acmicpc.net/problem/18511)
- 난이도 : 실버3 
- 시간 : 0 ms
- 메모리 : 2208KB
```cpp
#include <cmath>
int n, k, l, ans;
vector<int> v;
void dfs(int depth, int res) {
if (res > n) return;
ans = max(ans, res);
if (depth == l) {
return;
}
for (int i = 0; i < k; i++) {
dfs(depth + 1, res + (v[i] * pow(10, depth)));
}
return;
}
void solve() {
cin >> n >> k;
v.resize(k);
for (int i = 0; i < k; ++i) cin >> v[i];
for (int i = 1; i < 9; ++i) {
int temp = n / pow(10, i);
if (temp == 0) {
l = i;
break;
}
}
dfs(0, 0);
cout << ans << "\n";
return;
}
int main() {
solve();
return 0;
}
```
- 재귀에서 가장 중요한건, 종료 조건입니다. 사실 …

[Solve] : [BOJ] 18511 큰 수 구성하기 - 문제 해결

---

minwoo/BOJ/24053/sol.cpp

- 문제 : [알고리즘 수업 - 삽입 정렬 3](https://www.acmicpc.net/problem/24053)
- 플랫폼: 백준
- 난이도 : 골드 5
- 시간 : 0ms
- 메모리 : 2020KB
```cpp
int n, ans = 0;
vector<int> a;
vector<int> b;
void check_array() {
for (int i = 0; i < n; i++)
if (a[i] != b[i]) return;
ans = 1;
return;
}
void insertion_sort() {
check_array();
for (int i = 1; i < n; i++) {
int loc = i - 1;
int num = a[i];
while (0 <= loc and num < a[loc]) {
a[loc + 1] = a[loc];
check_array();
loc--;
}
if (loc + 1 != i) {
a[loc + 1] = num;
check_array();
}
}
}
void solve() {
cin >> n;
a.resize(n);
b.resize(n);
for (int i = 0; i < n; i++) cin >> a[i];
for (int i = 0; i < n; i++) cin >> b[i];
insertion_sort();
cout << ans << "\n";
return;
}
int main() {
ios::sync_with_stdio(false); …
```

[Solve] : [BOJ] 24053 알고리즘 수업 - 삽입 정렬 3 - 문제 해결

---

Comet/BOJ/21944/소스.cpp

- 문제 : [문제 추천 시스템 Version 2](https://www.acmicpc.net/problem/21944)
- 플랫폼: 백준
- 난이도 : 골드 2
- 시간 : 336ms
- 메모리 : 12180kb
```cpp
#include <set>
struct dataset
{
int num, difficulty;
bool operator < (const dataset& other) const {
if (difficulty == other.difficulty) {
return num < other.num;
}
return difficulty < other.difficulty;
}
};
struct memo
{
int difficulty = 0, algo = 0;
};
memo problems[100001];
set<dataset> list;
vector<set<dataset>> algo(101);
int main()
{	
int num, a, b, c;
cin >> num;
cin >> a >> b >> c;
list.insert({ a, b });
algo[c].insert({ a, b });
problems[a].difficulty = b;
problems[a].algo = c;
}
cin >> num;
string q;
cin >> q;
//cout …
```

[Solved] : BOJ21944 문제 추천 시스템 Version 2 문제 해결

---

sangGyenog/BOJ/1744/sol.java

- 문제 : [수 묶기](https://www.acmicpc.net/problem/1744)
- 플랫폼: 백준
- 난이도 : 골드 4
- 시간 : 108ms
- 메모리 : 14376KB
```java
/**
* 02:52
* 길이가 N인 수열이 주어짐 그 수열의 합을 구하려고 함
* 수열의 두 수를 묶음, 위치에 상관없이 묶기 가능
* 같은위치에 있는 자기자신은 묶는 건 불가
* 그리고 어떤 수를 묶게되면 수열의 합을 구할 때 묶은 수는 서로 곱한 후 묶음
* 수열의 모든 수는 한번만 묶거나 안 묶어야 함
* 이 방식을 사용해 최대가 되는 수 출력
*
* 입력
* 수열의 크기 N < 50
* N개의 줄에 수열의 각 수가 주어짐
* 수열의 수는 -1000 <= 수 <= 10000
*/
public class java250801_1744 {
int N = Integer.parseInt(br.readLine().trim());
int[] negative = new int[N]; //음수 저장용
int[] positive = new int[N]; // 2이상 저장용
int[] one = new int[N]; //1 저장용
int negativeIdx = 0; //음수개수
int oneIdx = 0; //1개수 …
```

[Solve]: [BOJ] 1744 수 묶기 - 문제해결

---

Comet/BOJ/21939/소스.cpp

- 문제 : [문제 추천시스템 Version 1](https://www.acmicpc.net/problem/21939)
- 난이도 : 골드 4
- 시간 : 248
- 메모리 :7040kb
```cpp
#include <set>
struct dataset
{
int num, difficulty;
bool operator < (const dataset& other) const {
if (difficulty == other.difficulty) {
return num < other.num;
}
return difficulty < other.difficulty;
}
};
int problems[100001] = { 0 };
set<dataset> list;
int main()
{
int num, a, b;
cin >> num;
cin >> a >> b;
list.insert({ a, b });
problems[a] = b;
}
cin >> num;
string q;
cin >> q;
if (q == "add") {
cin >> a >> b;
list.insert({ a, b });
problems[a] = b;
}
else if (q == "solved") {
cin >> a;
list.erase({ a, …
```

[Solved] : BOJ/21939 문제 추천시스템 Version 1 문제 해결

---

Comet/BOJ/21610/소스.cpp

- 문제 : [마법사 상어와 비바라기](https://www.acmicpc.net/problem/21610)
- 플랫폼: 백준
- 난이도 : 골드 5
- 시간 : 40ms
- 메모리 : 2160kb
```cpp
#include <set>
struct yx
{
int y, x;
bool operator<(const yx& b) const {
if (y == b.y) {
return x < b.x;
}
return y < b.y;
}
};
int length, moves;
vector<vector<int>> arr;
set<yx> clouds;
int dy[8] = {0, -1, -1, -1, 0, 1, 1, 1};
int dx[8] = {-1, -1, 0, 1, 1, 1, 0, -1};
void cloud_move(int dir, int num) {
set<yx> newClouds;
for (auto& cloud : clouds) {
int ny = cloud.y + dy[dir] * num;
int nx = cloud.x + dx[dir] * num;
ny = ny % length;
nx = nx % length;
if (ny < 0) {
ny += length;
}
if (nx < 0) {
nx += length;
}
newClouds.insert({ ny, nx });
}
swap(clouds, newClouds);
}
void rain() {
for (auto& cloud : clouds) { …
```

[Solved] : BOJ/21610 마법사 상어와 비바라기 문제 해결

---

sangGyenog/BOJ/5557/sol.java

- 문제 : [1학년](https://www.acmicpc.net/problem/5557)
- 플랫폼: 백준
- 난이도 : 골드 5
- 시간 : 100ms
- 메모리 : 14068KB
```java
/** 02:22
* 숫자열에서 마지막 두 숫자 사이에 =을 넣고
* 나머지에 +, -를 넣어 등식만들기
* 왼쪽부터 계산 식이 0이상 20이하, 출력도 포함
* 만들 수 있는 올바른 등식 개수 출력
*
* 입력
* 숫자의 개수 N
* 0이상 9이하 정수 N개
*/
public class java250806_5557 {
static int N = 0;
N = Integer.parseInt(br.readLine());
StringTokenizer st = new StringTokenizer(br.readLine());
int[] num = new int[N];
for(int i = 0 ; i < N;i++){
num[i] = Integer.parseInt(st.nextToken());
}
long[][] dp = new long[N][21]; //2차원으로 선언해주며 [i][j] i번째 숫자까지 계산을 마침
//i번째 숫자까지 계산했을 때 j인 경우의 수를 삽입, 2^63-1 이하라서 long으로 선언.. …
```

[Solve]: [BOJ] 5557 1학년 - 문제해결

---

Comet/BOJ/19236/sol.cpp

- 문제 : [청소년 상어](https://www.acmicpc.net/problem/19236)
- 플랫폼: 백준
- 난이도 : 골드 3
- 시간 : 0ms
- 메모리 : 2024kb
```cpp
const int length = 4;
const int SHARK = -1;
const int die = 0;
int dy[8] = { -1, -1, 0, 1, 1, 1, 0, -1 };
int dx[8] = { 0, -1, -1, -1, 0, 1, 1, 1 };
int result = 0;
struct dataset
{
int y, x, direc;
bool live = 1;
};
void print(vector<vector<int>>& arr) {
for (int i = 0; i < length; ++i) {
for (int j = 0; j < length; ++j) {
cout << arr[i][j] << ' ';
}
cout << endl;
}
cout << endl;
}
// 이동 가능위치 반환 함수.
vector<dataset> find(vector<vector<int>>& arr, vector<dataset>& fishes) {
auto& shark = fishes[0];
vector<dataset> new_loc;
int ny, nx;
for (int i = 1; i < 4; ++i) {
ny = shark.y + (dy[shark.direc] * i); …
```

[Solved] : BOJ/19236 청소년 상어 문제 풀이

---

minwoo/BOJ/2668/sol.cpp

- 문제 : [숫자고르기](https://www.acmicpc.net/problem/2668)
- 난이도 : 골드 5
- 시간 : 0mx
- 메모리 : 2024KB
```cpp
int n;
int v[109];
vector<int> ans;
void dfs(int startIndex, int curIndex, vector<bool>& visit) {
visit[curIndex] = true;
if (v[curIndex] == startIndex) {
ans.push_back(startIndex);
visit[curIndex] = false;
return;
}
int nextIndex = v[curIndex];
if (!visit[nextIndex])
dfs(startIndex, nextIndex, visit);
visit[curIndex] = false;
}
int main() {
cin >> n;
for (int i = 1; i <= n; ++i)
cin >> v[i];
for (int k = 1; k <= n; ++k) {
vector<bool> visit(n + 1, 0);
dfs(k, k, visit);
}
cout << ans.size() << "\n";
sort(ans.begin(), …
```

[Solve] : [BOJ] 2668 숫자고르기 - 문제 해결

---

Comet/BOJ/2169/소스.cpp

- 문제 : [로봇 조종하기 ](https://www.acmicpc.net/problem/2169)
- 플랫폼: 백준
- 난이도 : 골드 2
- 시간 : 188ms
- 메모리 :112252kb
```cpp
const int MIN = -1000000000;
int row, col;
int arr[1000][1000];
int dp[1000][1000][3];
bool visited[1000][1000] = { 0 };
int dy[3] = { 0, 0, 1 };
int dx[3] = { -1, 1, 0 };
int dfs(int y, int x, int direc) {
if (y == row - 1 && x == col - 1) {
return arr[y][x];
}
if (dp[y][x][direc] != MIN) return dp[y][x][direc];
int tempy, tempx, tempval;
for (int i = 0; i < 3; ++i) {
tempy = y + dy[i];
tempx = x + dx[i];
if (tempy < 0 || tempy >= row || tempx < 0 || tempx >= col || visited[tempy][tempx] == 1) continue;
visited[tempy][tempx] = 1;
int result = dfs(tempy, tempx, i);
dp[y][x][direc] = max(dp[y][x][direc], result + …
```

[solved] : BOJ/2169 로봇 조종하기 문제 해결

---

Comet/BOJ/2668/sol.cpp

- 문제 : [숫자고르기](https://www.acmicpc.net/problem/2668)
- 플랫폼: 백준
- 난이도 : 골드 5
- 시간 : 0ms
- 메모리 : 2024kb
```cpp
#include <cstring>
#include <set>
int num;
int arr[101];
bool visited[101] = { 0 };
bool same[101] = { 0 };
int sameCnt = 0;
int memo;
set<int> ans;
set<int> temp;
bool dfs(int n) {
if (visited[n] || same[n]) {
if (n != memo) return 0;
ans.insert(temp.begin(), temp.end());
return 1;
}
visited[n] = 1;
temp.insert(n);
if (!dfs(arr[n])) {
visited[n] = 0;
return 0;
}
return 1;
}
int main() {
cin >> num;
for (int i = 1; i <= num; ++i) {
cin >> arr[i];
if (i == arr[i]) {
++sameCnt;
same[i] = 1;
}
}
for (int i = 1; i <= num; ++i) {
if (same[i] || visited[i]) continue;
memo = i;
temp.clear();
memset(visited, 0, …
```

[Solved] : BOJ/2668 숫자고르기 문제 해결

---

sangGyenog/BOJ/11931/sol.java

- 문제 : [수 정렬하기 4](https://www.acmicpc.net/problem/11931)
- 플랫폼: 백준
- 난이도 : 실버 5
- 시간 : 1412ms
- 메모리 : 123224 KB
```java
/**
* 01:18
* N개의 수가 주어졌을 때 내림차순으로 정렬
* 입력
* 수의 개수 N
* N개의 줄에 걸쳐 숫자가 주어짐
* 1<= N <= 1000000
*/
public class java250731_11931 {
StringTokenizer st = new StringTokenizer(br.readLine());
StringBuilder sb = new StringBuilder();
int N = Integer.parseInt(st.nextToken());
int[] num = new int[N];
for(int tc = 0;tc < N;tc++){
st = new StringTokenizer(br.readLine());
num[tc] = Integer.parseInt(st.nextToken());
}
Arrays.sort(num); //정렬
//반대로 출력
for(int n=N-1;n>=0;n--){
sb.append(num[n]).append("\n");
} …
```

[Solve]: [BOJ] 11931 수 정렬하기 4 - 문제해결

---

sangGyenog/BOJ/3049/sol.java

- 문제 : [다각형의 대각선](https://www.acmicpc.net/problem/3049)
- 플랫폼: 백준
- 난이도 : 실버5
- 시간 : 108ms
- 메모리 : 14100KB
```java
/**
* 01:13
* 세 대각선이 한점에서 만나지 않는 볼록 N각형(모든 내부각이 180도 보다 작음)
* 대각선 교차점의 개수세서 출력
*/
public class java250722_3049 {
StringTokenizer st = new StringTokenizer(br.readLine());
int N = Integer.parseInt(st.nextToken());
System.out.println(N * (N - 1) * (N - 2) * (N - 3) / 24);
}
}
```
N각형을 그리며 대각선을 그려보고 든 아이디어는 각 꼭짓점을 1-N번을 잡고 map을 만들어 그을 수 있는 대각선을 리스트화해 value값으로 넣고 방문하는 방식으로 구하려고 했다. 하지만 시간복잡도가 O(n**4)이 나온다는 것을 알았고, 풀이를 참고했다.
먼저 사각형일 때 최초로 교차점이 1 나온다.  즉 4꼭짓점이 대각선으로 연결 시 교차점 1개가  나오니까 N개의 원소 중에서 순서 상관없이 4개를 고르는 방법의 …

[Solve]: [BOJ] 3049 다각형의 대각선 - 문제해결

---

Comet/BOJ/1504/소스.cpp

- 문제 : [특정한 최단 경로](https://www.acmicpc.net/problem/1504)
- 플랫폼: 백준
- 난이도 : 골드 4
- 시간 : 124 ms
- 메모리 : 6356 kb
```cpp
#include <climits>
int node_num, line_num;
int must[2];
struct lineData
{
int node, length;
};
struct queData
{
int node, length;
int visit;
};
struct compare
{
bool operator ()(const queData& a, const queData& b) {
return a.length > b.length;
}
};
vector<vector<lineData>> graph;
void dijk() {
vector<vector<int>> dist(node_num + 1, vector<int>(4, INT_MAX));
dist[1][0] = 0;
priority_queue<queData, vector<queData>, compare> que;
if (1 == must[0] ) {
que.push({ 1, 0, 1 });
}
else if (1 == must[1]) {
que.push({ 1, 0, 2 });
}
else {
que.push({ 1, 0, 0 });
}
que.push({ 1, 0, 0 });
queData cur;
while …
```

[Solved] : BOJ/1504 특정한 최단 경로 문제 해결

---

Comet/Programmers/12979/sol.cpp

- 문제 : [기지국 설치](https://chzzk.naver.com/live/0b33823ac81de48d5b78a38cdbc0ab94)
- 플랫폼: 프로그래머스
- 난이도 : 난이도 3
- 시간 : 
- 메모리 :
```cpp
int solution(int n, vector<int> stations, int w)
{
int answer = 0;
int left = 1;
int right = 0;
int range = w * 2 + 1;
for (auto& station : stations) {
left = station - w;
cout << answer << ' ' << left << ' ' << right << endl;
if (left <= right + 1) {
right = station + w;
continue;
}
int diff = left - right - 1;
answer += diff / range;
if (diff % range != 0) {
answer += 1;
}
right = station + w;
}
cout << answer << ' ' << left << ' ' << right << endl;
int diff = n - right;
if (right < n) {
answer += diff / range;
if (diff % range != 0) {
answer += 1;
}
}
// [실행] 버튼을 누르면 출력 값을 볼 수 있습니다.
cout << answer << …
```

[Solved] : Pgm/12979 기지국 설치 문제 해결

---

Comet/BOJ/1238/소스.cpp

- 문제 : [파티](https://www.acmicpc.net/problem/1238)
- 플랫폼: 백준
- 난이도 : 골드 3
- 시간 : 4ms
- 메모리 : 2288kb
```cpp
#include <climits>
struct dataset
{
int node, len;
};
struct compare
{
bool operator ()(const dataset& a, const dataset& b) {
return a.len > b.len;
}
};
int num, Lnum, Pnum;
void dijk(vector<vector<dataset>>& graph, vector<int>& dist) {
priority_queue<dataset,  vector<dataset>, compare> que;
dist[Pnum] = 0;
que.push({ Pnum, 0 });
dataset cur;
while (!que.empty())
{
cur = que.top(); que.pop();
if (cur.len > dist[cur.node]) continue;
for (auto& road : graph[cur.node]) {
int nextlen = cur.len + road.len;
if (nextlen > dist[road.node]) continue;
dist[road.node] = nextlen;
que.push({ road.node, nextlen });
}
}
} …
```

[Solved] : BOJ/1238 파티 문제 해결

---

Comet/BOJ/2056/소스.cpp

- 문제 : [작업](https://www.acmicpc.net/problem/2056)
- 플랫폼: 백준
- 난이도 : 골드 4
- 시간 : 168ms
- 메모리 : 2020kb
```cpp
struct dataset
{
int start = 0, end = 0;
};
int num;
int result = -1;
int main() {
cin >> num;
vector<dataset> works(num + 1);
int t, n, w;
for (int i = 1; i <= num; ++i) {
cin >> t >> n;
int min_time = 0;
for (int j = 0; j < n; ++j) {
cin >> w;
min_time = max(works[w].end, min_time);
}
works[i].start = min_time;
works[i].end = min_time + t;
result = max(works[i].end, result);
}
cout << result << '\n';
return 0;
}
```
* 선행 작업에 대해 탐색하며 가장 나중의 작업의 종료시간을 시작점으로 작업 스케줄 작성.
* 그와 동시에 가장 나중에 끝나는 작업의 시간을 갱신해감.
---

[Solved] : BOJ/2056 작업 문제 해결

---

sangGyenog/BOJ/20058/sol.java

- 문제 : [마법사 상어와 파이어스톰](https://www.acmicpc.net/problem/20058)
- 플랫폼: 백준
- 난이도 : 골드 3
- 시간 : 480ms
- 메모리 : 95344KB
```java
/**
* 03:36
* 2**n * 2**n 격자
* 각 위치에 얼음의 양이 있음
* 파이어스톰시전시 단계 L결정 필요
* 먼저 격자를 2**L * 2**L 크기의 부분격자로 나눔
* 모든 부분 격자를 오른쪽 90도 회전
* 얼음이 있는 칸 3개 또는 그 이상과 인접해있지 않은(상, 하, 좌, 우말고 나머지) 얼음의 양이 1줄어듦
* 파이어스톰을 통 Q번 시전한다고 할 때 모든 파이어 스톰이 끝난 후
* 1. 남은 얼음 A[r][c]의 합
* 2. 남은 얼음 중 가장 큰 덩어리가 차지하는 칸의 개수
* 을 출력 덩어리가 없으면 0
* 얼음이 있는 칸이 얼음이 있는 칸과 인접하면 연결되어 있는 것
*
* 입력
* N, Q
* 2**N개줄에 격자의 얼음정보가 주어짐
* 마법을 시전한 단계가 주어짐
*/
public class java250721_20058 {
static int[] x = {-1, 1, 0, 0};
static int[] y = {0, 0, -1, 1};
static int nPow = 0;
BufferedReader br = new BufferedReader(new …
```

[Solve]: [BOJ] 20058 마법사 상어와 파이어스톰 - 문제해결

---

Comet/BOJ/1759/소스.cpp

- 문제 : [암호 만들기](https://www.acmicpc.net/problem/1759)
- 플랫폼: 백준
- 난이도 : 골드 5
- 시간 : 0ms
- 메모리 : 2024kb
```cpp
int ans_num, num;
vector<char> alpha;
vector<char> fin = { 'a', 'e', 'i', 'o', 'u' };
void dfs(vector<char>& arr, int cnt, int idx) {
if (cnt == ans_num) {
int many = 0;
for (auto& c : arr) {
for (auto& f : fin) {
if (c == f) {
many++;
break;
}
}
}
if (many == 0 || (arr.size() - many) < 2) {
return;
}
for (auto& c : arr) {
cout << c;
}
cout << '\n';
return;
}
if (idx == num) {
return;
}
arr.push_back(alpha[idx]);
dfs(arr, cnt + 1, idx + 1);
arr.pop_back();
dfs(arr, cnt, idx + 1);
}
int main() {
cin >> ans_num >> num;
char input;
cin >> input;
alpha.push_back(input);
} …
```

[Solved] : BOJ/1759  암호 만들기 문제 해결

---

minwoo/BOJ/11931/sol.cpp

- 문제 : [수 정렬하기 4](https://www.acmicpc.net/problem/11931)
- 플랫폼: 백준
- 난이도 : 실버5
- 시간 : 300ms
- 메모리 : 5928KB
```cpp
struct Data {
int i;
bool operator<(const Data& other) const {
return i > other.i;
}
};
void solve() {
int n;
cin >> n;
vector<Data> v(n);
for (int i = 0; i < n; i++) cin >> v[i].i;
sort(v.begin(), v.end());
for (int i = 0; i < n; i++) cout << v[i].i << "\n";
return;
}
int main() {
solve();
return 0;
}
```
- 역시 python이 좋아요
---

[Solve] : [BOJ] 11931 수 정렬하기 - 문제 해결

---

sangGyenog/BOJ/16235/sol.java

- 문제 : [나무재테크](https://www.acmicpc.net/problem/16235)
- 플랫폼: 백준
- 난이도 : 골드3
- 시간 : 1032ms
- 메모리 : 299004KB
```java
/**
* 02:34
* NxN크기의 땅을 구매함
* 땅을 1x1크기 칸으로 나눔 각각 칸은 (r, c)로 나타냄
* 땅의 양분을 조사하는 로봇이 있다
* 처음 모든 땅의 양분은 5
* M개의 나무를 구매해 키운 후 파는 재테크
* 같은 칸에 여러 나무가 있을 수 있다
*
* 과정
* 1. 봄 - 나무가 자신의 나이만큼 양분을 먹고 나이 +1 자기칸에 있는 양분만 먹을 수 있음
* 여러 나무가 있다면 나이가 어린 나무부터 양분을 먹음
* 양분부족 시 자신의 나이만큼 못먹는 나무는 죽음
* 2. 여름 - 봄에 죽은 나무가 양분으로 변함 죽은 나무마다 나이를 2로 나눈 값이 나무가 있던 칸에 양분으로 추가
* 소수점 아래는 버림
* 3. 가을 - 나무 번식, 번식하는 나무는 나이가 5의 배수, 인접한 8개 칸에 나이가 1인 나무가 생김
* 4. 겨울 - 양분을 조사하는 로봇이 양분을 추가함, 각 칸에 추가되는 양분은 입력으로 주어지는 A[r][c]
*
* K년이 지난 후 살아있는 나무의 개수 출력
*
* 입력
* N, M, K
* N개의 줄에 걸쳐 A배열 값이 주어짐
* M개의 줄에 걸쳐 나무 정보를 나타내는 X, y, z
* x, y는 위치 / z는 나이임
*
*/
public class java250716_16235 {
public …
```

[Solve]: [BOJ] 16235 나무재테크 - 문제해결

---

sangGyenog/BOJ/12919/sol.java

- 문제 : [A와 B 2](https://www.acmicpc.net/problem/12919)
- 플랫폼: 백준
- 난이도 : 골드 5
- 시간 : 104ms
- 메모리 : 14196KB
```java
/**
* 01:07
* A B로만 이루어진 두 문자열 S, T
* S를 T로 바꿀 수 있으면 1 아니면 0출력
* 1. 문자열 뒤에 A추가
* 2. 문자열 뒤에 B를 추가하고 문자열을 뒤집는다
* S길이 < T길이
*/
public class java250719_12919 {
static String S; //입력1
static String T; //입력2
static int rst = 0; //S -> T 가능여부
S = br.readLine();
T = br.readLine();
bfs(T); //효율성을 위해 T -> S 역으로 접근
System.out.println(rst);
}
static void bfs(String word){
Queue<String> q = new LinkedList<>();
q.add(word);
while(!q.isEmpty()){
String qWord = q.poll();
if(qWord.length() < S.length()) continue; …
```

[Solve]: [BOJ] 12919 A와 B 2 - 문제해결

---

sangGyenog/BOJ/9372/sol.java

- 문제 : [상근이의 여행](https://www.acmicpc.net/problem/9372)
- 플랫폼: 백준
- 난이도 : 실버 4
- 시간 : 456ms
- 메모리 : 59764KB
```java
/**
* 02:20
* N개국을 여행하는데 가장 적은 종류의 비행기를 타고 국가를 이동
* 이를 출력
* 다른 국가를 거쳐가도 이미 방문한 곳이어도 됨
*
* 입력
* 테케 수 T
* 국가의 수N, 비행기 종류 M
* M개의 줄에 a, b의 쌍이 입력
* a와 b를 왕복하는 비행기가 있다는 것을 의미
* 항상 연결 그래프를 이룸
*
* 출력
* 테스트 케이스마다 한 줄을 출력
* 모든 국가를 여행하기 위해 타야하는 비행기 종류의 최소 개수
*/
public class java250718_9372 {
static int rst = 0;
StringTokenizer st = new StringTokenizer(br.readLine());
int T = Integer.parseInt(st.nextToken());
for(int tc=0;tc<T;tc++){
st = new StringTokenizer(br.readLine());
int N = Integer.parseInt(st.nextToken()), M = …
```

[Solve]: [BOJ] 9372 상근이의 여행 - 문제해결

---

Comet/BOJ/12919/sol.cpp

- 문제 : A와 B 2https://www.acmicpc.net/problem/12919
- 플랫폼: 백준
- 난이도 : 골드 5
- 시간 : 0ms
- 메모리 : 2024 kb
```cpp
string arr;
string tar;
bool result = 0;
void dfs(string st) {
if (arr.size() == st.size()) {
int size = st.size();
for (int i = 0; i < size; ++i) {
if (st[i] != arr[i]) {
return;
}
}
result = 1;
return;
}
string temp = st;
if (temp.back() == 'A') {
temp.pop_back();
dfs(temp);
}
temp = st;
if (temp.front() == 'B') {
reverse(temp.begin(), temp.end());
temp.pop_back();
dfs(temp);
}
}
int main() {
cin >> arr >> tar;
dfs(tar);
cout << result << '\n';
return 0;
}
```
* 첨에 브루트포스 했다가 피 많이 봤습니다.
* 역순으로 탐색해서 원본이 될 수 있는지 확인했어요
---

[Solved] : BOJ/12919 A와 B 2 문제 해결

---

minwoo/BOJ/20058/sol.cpp

- 문제 : [마법사 상어와 파이어스톰](https://www.acmicpc.net/problem/20058)
- 플랫폼: 백준
- 난이도 : 골드 3
- 시간 : 120ms
- 메모리 : 2348KB
```cpp
#include <cmath>
int n, q, l, k;
vector<vector<int>> a;
void rotate_array(int r_start, int c_start, int grid_size) {
vector<vector<int>> v(grid_size, vector<int>(grid_size));
for (int i = 0; i < grid_size; ++i)
for (int j = 0; j < grid_size; ++j)
v[i][j] = a[r_start + i][c_start + j];
for (int i = 0; i < grid_size; ++i)
for (int j = 0; j < grid_size; ++j)
a[r_start + j][c_start + grid_size - 1 - i] = v[i][j];
return;
}
void firestorm_rotate(int cur_l_level, int r, int c, int grid_size) {
if (cur_l_level == l) {
rotate_array(r, c, grid_size);
return;
}
int half_gird_size = …
```

[Solve] : [BOJ] 20058 마법사 상어와 파이어스톰 - 문제 해결
